import { BUSINESS, FILE, MASTER, NET, NET_ENDPOINTS, NET_FUNCTION_GET_JWT, SMALL, } from "@/conf/conf-net";
import Net from "./net";

// 主数据源
export const master = new Net(
    NET.MASTER.URI + '/' + NET.MASTER.API, 
    NET_ENDPOINTS[ MASTER ], 
    NET_FUNCTION_GET_JWT,
    NET.MASTER.TIMEOUT_GET, NET.MASTER.TIMEOUT_POS, NET.MASTER.IS_LOG
);

// 小程序
export const small = new Net(
    NET.SMALL.URI + '/' + NET.SMALL.API, 
    NET_ENDPOINTS[ SMALL ], 
    NET_FUNCTION_GET_JWT,
    NET.SMALL.TIMEOUT_GET, NET.SMALL.TIMEOUT_POS, NET.SMALL.IS_LOG
);

// 商业数据源
export const business = new Net(
    NET.BUSINESS.URI + '/' + NET.BUSINESS.API, 
    NET_ENDPOINTS[ BUSINESS ], 
    NET_FUNCTION_GET_JWT,
    NET.BUSINESS.TIMEOUT_GET, NET.BUSINESS.TIMEOUT_POS, NET.BUSINESS.IS_LOG
);

// 文件上传
export const file = new Net(
    NET.FILE.URI + '/' + NET.FILE.API, 
    NET_ENDPOINTS[ FILE ], 
    NET_FUNCTION_GET_JWT,
    NET.FILE.TIMEOUT_GET, NET.FILE.TIMEOUT_POS, NET.FILE.IS_LOG
);